"use client";

import { Navbar } from "@/components/navigation/navbar";
import { StarBackground } from "@/components/ui/star-background";
import { cn } from "@/lib/utils";
import { Inter } from "next/font/google";
import "./globals.css";
import { useInertiaScroll } from "@/hooks/use-inertia-scroll";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  useInertiaScroll();

  return (
    <html lang="en" className="dark">
      <body className={cn(inter.className, "min-h-screen bg-background")}>
        <Navbar />
        <StarBackground />
        {children}
      </body>
    </html>
  );
}
